services:
    vector_store:
        image: qdrant/qdrant
        container_name: support-agent-qdrant
        volumes:
            - ./data/qdrant:/qdrant/storage
        ports:
           - "6333:6333"
        networks:
            - default

    postgresql:
        image: postgres:17
        container_name: support-agent-postgresql
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - default

    app:
        &app
        image: python:3.12
        build: .
        env_file: &env_file
            - .env
        depends_on: &depends_on
            - postgresql
            - vector_store
        networks: &networks
            - default

    app_migration:
        <<: *app
        env_file: *env_file
        depends_on: *depends_on
        networks: *networks
        command: ["alembic", "upgrade", "head"]

    app_fill_vector_store:
        <<: *app
        env_file: *env_file
        depends_on: *depends_on
        networks: *networks
        command: ["python", "commands/confluence_qdrant.py"]

    nginx:
        image: nginx
        ports:
            - "5000:5000"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - app
        networks:
            - default

networks:
    default:
        name: support_agent_net
        external: true
